/**
 * 드라이버 목업 데이터
 * 고객 차량을 대신 운전해주는 서비스 제공자들
 */
import { ImageSourcePropType } from 'react-native';
import { D1, D2, D3, D4, D5, D6 } from './photos';
import { DriverServiceKind, DrivableVehicleType, TransmissionSkill } from '../types';

export interface MockDriver {
  id: string;
  name: string;
  firstName: string;
  photo: ImageSourcePropType;
  location: string;
  lat?: number;
  lng?: number;
  rating: number;
  pricePerHour: number;
  totalJobs: number;
  isAvailable: boolean;
  isVerified: boolean;
  experienceYears: number;
  drivableTypes: DrivableVehicleType[];
  transmission: TransmissionSkill;
  services: DriverServiceKind[];
  licenseClass: string;    // SIM A, SIM B1 등
  temperature: number;     // Linka 온도
}

export const MOCK_DRIVERS: MockDriver[] = [
  {
    id: 'd1', name: 'Imam Wahyudi', firstName: 'Imam',
    photo: D1, location: 'Kebayoran Baru',
    lat: -6.2474, lng: 106.8005,
    rating: 4.6, pricePerHour: 30000, totalJobs: 241,
    isAvailable: true, isVerified: true, experienceYears: 7,
    drivableTypes: ['sedan', 'suv', 'mpv', 'van'], transmission: 'both',
    services: ['designated', 'daily', 'intercity'],
    licenseClass: 'SIM A',
    temperature: 76.5,
  },
  {
    id: 'd2', name: 'Aji Permana', firstName: 'Aji',
    photo: D2, location: 'Senopati',
    lat: -6.2449, lng: 106.8011,
    rating: 4.5, pricePerHour: 50000, totalJobs: 140,
    isAvailable: true, isVerified: true, experienceYears: 4,
    drivableTypes: ['suv', 'mpv', 'van'], transmission: 'both',
    services: ['daily'],
    licenseClass: 'SIM A',
    temperature: 64.1,
  },
  {
    id: 'd3', name: 'Nurhasan', firstName: 'Nurhasan',
    photo: D3, location: 'Cilandak',
    lat: -6.2535, lng: 106.8022,
    rating: 4.8, pricePerHour: 26000, totalJobs: 216,
    isAvailable: true, isVerified: true, experienceYears: 7,
    drivableTypes: ['sedan', 'suv', 'mpv', 'van'], transmission: 'both',
    services: ['designated'],
    licenseClass: 'SIM A',
    temperature: 74.8,
  },
  {
    id: 'd4', name: 'Masrur', firstName: 'Masrur',
    photo: D4, location: 'Pondok Indah',
    lat: -6.2457, lng: 106.8003,
    rating: 4.8, pricePerHour: 30000, totalJobs: 222,
    isAvailable: true, isVerified: true, experienceYears: 7,
    drivableTypes: ['sedan', 'suv', 'mpv'], transmission: 'both',
    services: ['designated', 'intercity', 'event', 'daily'],
    licenseClass: 'SIM A',
    temperature: 66.1,
  },
  {
    id: 'd5', name: 'Febry', firstName: 'Febry',
    photo: D5, location: 'Kemang',
    lat: -6.2442, lng: 106.8036,
    rating: 4.5, pricePerHour: 30000, totalJobs: 172,
    isAvailable: false, isVerified: true, experienceYears: 4,
    drivableTypes: ['mpv'], transmission: 'both',
    services: ['designated', 'daily', 'hourly', 'intercity', 'event'],
    licenseClass: 'SIM A',
    temperature: 66.1,
  },
  {
    id: 'd6', name: 'Galih Nurgalih', firstName: 'Galih',
    photo: D6, location: 'Menteng',
    lat: -6.2457, lng: 106.8075,
    rating: 5.0, pricePerHour: 25000, totalJobs: 98,
    isAvailable: true, isVerified: true, experienceYears: 2,
    drivableTypes: ['sedan', 'suv', 'mpv'], transmission: 'both',
    services: ['daily', 'intercity'],
    licenseClass: 'SIM B I',
    temperature: 59.0,
  },
  {
    id: 'd7', name: 'Taufik Hidayat', firstName: 'Taufik',
    photo: D1, location: 'Fatmawati',
    lat: -6.2455, lng: 106.8064,
    rating: 4.8, pricePerHour: 25000, totalJobs: 115,
    isAvailable: true, isVerified: true, experienceYears: 2,
    drivableTypes: ['sedan', 'suv', 'mpv'], transmission: 'both',
    services: ['designated', 'daily', 'intercity'],
    licenseClass: 'SIM A',
    temperature: 48.9,
  },
  {
    id: 'd8', name: 'Nandang Ahmad Yani', firstName: 'Nandang',
    photo: D2, location: 'Pejaten',
    lat: -6.2515, lng: 106.8031,
    rating: 4.6, pricePerHour: 30000, totalJobs: 210,
    isAvailable: false, isVerified: true, experienceYears: 7,
    drivableTypes: ['sedan', 'suv', 'mpv'], transmission: 'both',
    services: ['daily', 'intercity', 'designated'],
    licenseClass: 'SIM B I',
    temperature: 68.6,
  },
  {
    id: 'd9', name: 'Fazri', firstName: 'Fazri',
    photo: D3, location: 'Cipete',
    lat: -6.2474, lng: 106.8038,
    rating: 4.6, pricePerHour: 25000, totalJobs: 143,
    isAvailable: true, isVerified: true, experienceYears: 4,
    drivableTypes: ['sedan', 'suv'], transmission: 'both',
    services: ['designated', 'daily', 'hourly', 'intercity'],
    licenseClass: 'SIM A',
    temperature: 72.7,
  },
  {
    id: 'd10', name: 'Andreas Noto Nugroho', firstName: 'Andreas',
    photo: D4, location: 'Radio Dalam',
    lat: -6.2473, lng: 106.8063,
    rating: 4.9, pricePerHour: 30000, totalJobs: 213,
    isAvailable: true, isVerified: true, experienceYears: 7,
    drivableTypes: ['sedan'], transmission: 'both',
    services: ['designated', 'daily', 'hourly', 'airport', 'commute', 'intercity', 'event'],
    licenseClass: 'SIM A',
    temperature: 70.6,
  },
  {
    id: 'd11', name: 'Ilham Faiz Pratama', firstName: 'Ilham',
    photo: D5, location: 'Blok M',
    lat: -6.2439, lng: 106.8066,
    rating: 4.8, pricePerHour: 25000, totalJobs: 172,
    isAvailable: true, isVerified: true, experienceYears: 4,
    drivableTypes: ['sedan', 'suv', 'mpv'], transmission: 'both',
    services: ['designated', 'daily', 'hourly', 'intercity'],
    licenseClass: 'SIM A',
    temperature: 69.5,
  },
  {
    id: 'd12', name: 'M. Iqbal', firstName: 'Iqbal',
    photo: D6, location: 'Gandaria',
    lat: -6.2515, lng: 106.8005,
    rating: 4.6, pricePerHour: 30000, totalJobs: 140,
    isAvailable: true, isVerified: true, experienceYears: 4,
    drivableTypes: ['sedan', 'suv', 'mpv', 'van'], transmission: 'both',
    services: ['designated', 'daily', 'hourly', 'airport', 'commute', 'intercity', 'event'],
    licenseClass: 'SIM A',
    temperature: 72.9,
  },
  {
    id: 'd13', name: 'Rizki Fauzi', firstName: 'Rizki',
    photo: D1, location: 'Mampang',
    lat: -6.2450, lng: 106.8033,
    rating: 4.7, pricePerHour: 30000, totalJobs: 250,
    isAvailable: true, isVerified: true, experienceYears: 7,
    drivableTypes: ['sedan', 'suv', 'mpv', 'van'], transmission: 'both',
    services: ['designated', 'daily', 'hourly', 'airport', 'commute', 'intercity', 'event'],
    licenseClass: 'SIM A',
    temperature: 72.2,
  },
  {
    id: 'd14', name: 'Zaenal Arifin', firstName: 'Zaenal',
    photo: D2, location: 'Tebet',
    lat: -6.2512, lng: 106.8027,
    rating: 4.6, pricePerHour: 25000, totalJobs: 109,
    isAvailable: true, isVerified: true, experienceYears: 2,
    drivableTypes: ['sedan', 'mpv'], transmission: 'both',
    services: ['designated', 'daily', 'hourly', 'airport', 'commute', 'intercity', 'event'],
    licenseClass: 'SIM A',
    temperature: 66.0,
  },
  {
    id: 'd15', name: 'Achmad Rozali', firstName: 'Achmad',
    photo: D3, location: 'Pancoran',
    lat: -6.2498, lng: 106.8024,
    rating: 4.8, pricePerHour: 30000, totalJobs: 209,
    isAvailable: true, isVerified: true, experienceYears: 7,
    drivableTypes: ['sedan', 'suv', 'mpv'], transmission: 'both',
    services: ['designated', 'daily', 'hourly', 'airport', 'intercity', 'event'],
    licenseClass: 'SIM A',
    temperature: 63.9,
  },
  {
    id: 'd16', name: 'Adi Doris Siswanto', firstName: 'Adi',
    photo: D4, location: 'Kebayoran Baru',
    lat: -6.2527, lng: 106.8065,
    rating: 4.7, pricePerHour: 25000, totalJobs: 208,
    isAvailable: true, isVerified: true, experienceYears: 7,
    drivableTypes: ['sedan', 'suv', 'mpv', 'van'], transmission: 'both',
    services: ['designated', 'daily', 'hourly', 'airport', 'commute', 'intercity', 'event'],
    licenseClass: 'SIM A',
    temperature: 70.6,
  },
  {
    id: 'd17', name: 'Ade Irmawan', firstName: 'Ade',
    photo: D5, location: 'Senopati',
    lat: -6.2438, lng: 106.8055,
    rating: 4.9, pricePerHour: 25000, totalJobs: 205,
    isAvailable: true, isVerified: true, experienceYears: 7,
    drivableTypes: ['sedan'], transmission: 'both',
    services: ['designated', 'daily', 'hourly', 'airport', 'intercity'],
    licenseClass: 'SIM A',
    temperature: 77.4,
  },
  {
    id: 'd18', name: 'Raihan Lutfiansyah', firstName: 'Raihan',
    photo: D6, location: 'Cilandak',
    lat: -6.2470, lng: 106.8056,
    rating: 4.8, pricePerHour: 30000, totalJobs: 210,
    isAvailable: true, isVerified: true, experienceYears: 7,
    drivableTypes: ['sedan', 'suv', 'mpv', 'van'], transmission: 'both',
    services: ['designated', 'daily', 'hourly', 'airport', 'commute', 'intercity', 'event'],
    licenseClass: 'SIM A',
    temperature: 71.7,
  },
  {
    id: 'd19', name: 'Endang Setiawan', firstName: 'Endang',
    photo: D1, location: 'Pondok Indah',
    lat: -6.2493, lng: 106.8097,
    rating: 4.6, pricePerHour: 25000, totalJobs: 155,
    isAvailable: true, isVerified: true, experienceYears: 4,
    drivableTypes: ['sedan', 'suv', 'mpv'], transmission: 'both',
    services: ['designated', 'daily', 'hourly', 'airport', 'commute', 'intercity', 'event'],
    licenseClass: 'SIM A',
    temperature: 57.6,
  },
  {
    id: 'd20', name: 'Lukman Nur Hakim', firstName: 'Lukman',
    photo: D2, location: 'Kemang',
    lat: -6.2447, lng: 106.8089,
    rating: 4.8, pricePerHour: 25000, totalJobs: 110,
    isAvailable: true, isVerified: true, experienceYears: 2,
    drivableTypes: ['sedan'], transmission: 'both',
    services: ['designated', 'daily', 'hourly', 'intercity'],
    licenseClass: 'SIM A',
    temperature: 51.1,
  },
  {
    id: 'd21', name: 'Mardiansyah', firstName: 'Mardiansyah',
    photo: D3, location: 'Menteng',
    lat: -6.2462, lng: 106.8056,
    rating: 4.8, pricePerHour: 25000, totalJobs: 130,
    isAvailable: true, isVerified: true, experienceYears: 4,
    drivableTypes: ['sedan', 'suv', 'mpv'], transmission: 'both',
    services: ['designated', 'daily', 'hourly', 'airport', 'commute', 'intercity', 'event'],
    licenseClass: 'SIM A',
    temperature: 60.5,
  },
  {
    id: 'd22', name: 'Epen Boy', firstName: 'Epen',
    photo: D4, location: 'Fatmawati',
    lat: -6.2536, lng: 106.8095,
    rating: 4.9, pricePerHour: 70000, totalJobs: 220,
    isAvailable: true, isVerified: true, experienceYears: 7,
    drivableTypes: ['mpv', 'sedan', 'suv', 'van'], transmission: 'both',
    services: ['designated', 'daily', 'hourly', 'airport', 'commute', 'intercity', 'event'],
    licenseClass: 'SIM A',
    temperature: 64.2,
  },
  {
    id: 'd23', name: 'Sholeh Amin', firstName: 'Sholeh',
    photo: D5, location: 'Pejaten',
    lat: -6.2450, lng: 106.8097,
    rating: 4.7, pricePerHour: 25000, totalJobs: 83,
    isAvailable: false, isVerified: true, experienceYears: 2,
    drivableTypes: ['van'], transmission: 'both',
    services: ['designated', 'daily', 'hourly', 'airport', 'commute', 'intercity', 'event'],
    licenseClass: 'SIM A',
    temperature: 63.2,
  },
  {
    id: 'd24', name: 'Asep Mulyana', firstName: 'Asep',
    photo: D6, location: 'Cipete',
    lat: -6.2461, lng: 106.8015,
    rating: 4.8, pricePerHour: 25000, totalJobs: 218,
    isAvailable: true, isVerified: true, experienceYears: 7,
    drivableTypes: ['van'], transmission: 'both',
    services: ['designated', 'daily', 'hourly', 'airport', 'commute', 'intercity', 'event'],
    licenseClass: 'SIM A',
    temperature: 80.4,
  },
];

export const DRIVER_SERVICE_META: Record<DriverServiceKind, { icon: string; bg: string; color: string }> = {
  designated: { icon: 'moon-outline',      bg: '#F5F3FF', color: '#7C3AED' },
  daily:      { icon: 'sunny-outline',     bg: '#FFF7ED', color: '#F59E0B' },
  hourly:     { icon: 'time-outline',      bg: '#EFF6FF', color: '#2563EB' },
  commute:    { icon: 'repeat-outline',    bg: '#F0FDF4', color: '#16A34A' },
  airport:    { icon: 'airplane-outline',  bg: '#E0F2FE', color: '#0284C7' },
  intercity:  { icon: 'map-outline',       bg: '#FEF3C7', color: '#B45309' },
  event:      { icon: 'heart-outline',     bg: '#FDE2E4', color: '#DB2777' },
};
